### ISSUE TITLE
Font type isn't discussed

### ISSUE THREAD

**Issue by davidvedvick** [NancyFx/Nancy.Portfolio#2]
Would like to use the font type in a presentation - however it's not discussed in the README or in the Guidelines.

**Comment by thecodejunkie** [comment]
We're using a commercial font that is not freely available. What is it that you wish to do?

**Comment by davidvedvick** [comment]
Oh that's too bad! Just wanted to use it rather than include the Nancy
`png` banners everywhere. Thanks!

David Vedvick

Software Developer

www.davidvedvick.info

On Mon, Jun 27, 2016 at 4:50 PM, Andreas Håkansson <notifications@github.com

**Comment by xt0rted** [comment]
@thecodejunkie following up from https://github.com/NancyFx/Nancy/issues/2759#issuecomment-306919984, could the name of the font and where to get it be added just as a point of reference? If it's available on https://www.fonts.com/ I'd be able to help with the mockups as I have access to their fonts.

**Comment by thecodejunkie** [comment]
Sorry, but we've decided to not release the name of the font we're using - Unlike everything else with Nancy. the logo is not MIT and is subject to Copyright and we'd like to keep the number of "rouge" nancy designs to a minimum. We've released the font usage guidelines and we'd like to see them being used, instead of people creating their own variations for their own purposes

I'm not specifically talking about this https://github.com/NancyFx/Nancy/issues/2759#issuecomment-306919984) issue, but in more general terms
